name: prado_negocios
description: "Um aplicativo de classificados para a cidade de Prado."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0

  # Imagens
  image_picker: ^1.1.2
  image: ^4.2.0
  path_provider: ^2.1.3

  # Utilitários
  uuid: ^4.4.0
  provider: ^6.1.2
  intl: ^0.19.0
  timeago: ^3.6.1
  google_fonts: ^6.2.1 # <-- NOVO PACOTE

  # Ícones
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
