// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFw3VZEwgpElxT7IkxY3RTC7eUZGV6-g',
    appId: '1:4899689968:web:1c53bc1d23668d1924f935',
    messagingSenderId: '4899689968',
    projectId: 'pradonegocios1',
    authDomain: 'pradonegocios1.firebaseapp.com',
    storageBucket: 'pradonegocios1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6g5_UerioEq6greyQOHLlA7wwyEdRGTg',
    appId: '1:4899689968:android:4af7ec88d1b17ee424f935',
    messagingSenderId: '4899689968',
    projectId: 'pradonegocios1',
    storageBucket: 'pradonegocios1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDokNVprMgj1kvZ1B9JjRQdE-uFU9iBJdU',
    appId: '1:4899689968:ios:463fc3e4a96ad3b524f935',
    messagingSenderId: '4899689968',
    projectId: 'pradonegocios1',
    storageBucket: 'pradonegocios1.firebasestorage.app',
    iosBundleId: 'com.example.pradoNegocios',
  );

}